version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: js-heroes-postgres-dev
    environment:
      POSTGRES_DB: js-heroes-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-js-heroes:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d js-heroes-backend']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data-js-heroes: